### ISSUE TITLE
eSynth is not on github?

### ISSUE THREAD

**Issue by UnixJunkie** [liutairan/eMolFrag#2]
Is eMolFrag any useful without eSynth?

Thanks!
Francois.

**Comment by liutairan** [comment]
Hi Francois, eSynth can be found at [~~https://github.com/wcatykid/Graph-Based-Molecular-Synthesis~~](https://github.com/wcatykid/Graph-Based-Molecular-Synthesis). We used to have it on Dr. Brylinski's website, there is also a link to it. However, I just noticed that the old website was down. I will try to reach out to check what's going on with the tools.

**Comment by liutairan** [comment]
I will create a new repository for updated eSynth today with my account. I will let you know when I am ready. Thanks for your attention.

**Comment by liutairan** [comment]
Updated eSynth can be found at [https://github.com/liutairan/eSynth](https://github.com/liutairan/eSynth). I will write a manual with settings and examples later today or this weekend since I have some deadlines today and tomorrow. Thank you. 

Please let me know if you have further questions with eMolFrag or eSynth.
